name: Update README

on:
  schedule:
    - cron: '12 10 * * *'
    - cron: '25 10 * * *'
    - cron: '55 10 * * *'
    - cron: '25 11 * * *'
    - cron: '55 11 * * *'

jobs:
  make-contribution:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Make changes
        run: |
          echo "Making daily contribution on $(date)" >> README.md
          git add README.md
          git commit -m "Daily contribution on $(date)"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          branch: master
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Open pull request
        uses: peter-evans/create-pull-request@v3
        with:
          title: "Daily Contribution"
          commit-message: "Daily contributions"
          branch: master
          base: main
          body: "This pull request was created automatically by a GitHub Actions workflow to make daily contributions."
          token: ${{ secrets.GITHUB_TOKEN }}
